remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
title: [Mitt lille vindu ut i verden]
description: [Her vil det komme uregelmessige små bloggposter. Mest ment som en huskelapp til meg selv  men kanskje andre kan ha nytte av det også.]
show_downloads: false
google_analytics: 
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-WREQTJQZWG"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-WREQTJQZWG');
</script>
